### ISSUE TITLE
Hi, couple years ago you worked on Fairbrix blockchain, can you provide me some tokens for development please?

### ISSUE THREAD

**Issue by potatodata** [johndpope/SwiftTorch#1]

**Comment by johndpope** [comment]
hi sorry - no idea. I played around with a lot of few years back.
one thing I recall - finding the keys in previous git commits that were subsequently deleted.
good luck.

**Comment by potatodata** [comment]
thanks, may check out, current price 0.2 per token. If get some, don't forget to share, just saying :)
